<li class="">
                    <div class="pic"> <a href="[field:arcurl/]" target="_blank"><img onload="loadImage(this,384,262);" src="[field:litpic/]" /></a> <a href="[field:arcurl/]" target="_blank">
                      <div class="ball_box"></div>
                      </a> </div>
                    <div class="word clearfix"> <a href="[field:arcurl/]" target="_blank"> <span>[field:title/]</span> <b></b> </a> </div>
                  </li>