<?php
$z[0]=Array("global","",259,285);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("field","",762,781);
$z[1][4]['name']="title";
$z[2]=Array("global","",782,808);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",849,871);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",911,962);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",1111,1146);
$z[5][4]['filename']="head.htm";
$z[6]=Array("channel","\r\n      <a href='[field:typeurl/]'>[field:typename/]</a>\r\n      ",1515,1699);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a href='~typelink~' class='curr'>~typename~</a>";
$z[7]=Array("field","",1773,1792);
$z[7][4]['name']="title";
$z[8]=Array("field","",1812,1837);
$z[8][4]['name']="description";
$z[9]=Array("field","",1954,1972);
$z[9][4]['name']="body";
$z[10]=Array("field","",2062,2082);
$z[10][4]['name']="weburl";
$z[11]=Array("include","",2347,2384);
$z[11][4]['filename']="footer.htm";

?>