<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",48,76);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",93,122);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n                    <li><a href=\"[field:typelink/]\" target=\"_self\">[field:typename/]</a></li>\r\n                    ",197,367);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>