<li class="{dede:field.currentstyle/}"><a href="{dede:field name='typeurl'/}" target="_self">{dede:field name='typename'/}</a>
                <div>
                    <ul>
                    {dede:channel type='son' noself='yes'}
                    <li><a href="[field:typelink/]" target="_self">[field:typename/]</a></li>
                    {/dede:channel}
                    </ul>
                </div>
                </li>