<li>
              <div class="img"><img src="[field:litpic/]" onload="loadImage(this,165,123)" alt="[field:fulltitle/]" onerror="loadImageError(this,'.img')"></div>
              <div class="t-content">
                <div class="name"><a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank">[field:title/]</a></div>
                <p class="txt">[field:description/]</p>
                <div class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
              </div>
            </li>