<?php
$z[0]=Array("flink","[field:link/]",222,260);
$z[1]=Array("channel","\r\n       <a href=\"[field:typelink/]\" target=\"_self\"><span>[field:typename/]</span></a>\r\n        ",386,546);
$z[1][4]['typeid']="1";
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("global","",689,711);
$z[2][4]['name']="address";
$z[3]=Array("global","",781,807);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",856,880);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",1005,1024);
$z[5][4]['name']="fwrx";
$z[6]=Array("global","",1093,1113);
$z[6][4]['name']="email";
$z[7]=Array("global","",1678,1695);
$z[7][4]['name']="qq";
$z[8]=Array("global","",1867,1886);
$z[8][4]['name']="fwrx";
$z[9]=Array("global","",1942,1961);
$z[9][4]['name']="jszc";

?>