<?php
$z[0]=Array("flink","[field:link/]",222,260);
$z[1]=Array("channel","\r\n       <a href=\"[field:typelink/]\" target=\"_self\"><span>[field:typename/]</span></a>\r\n        ",384,544);
$z[1][4]['typeid']="1";
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("global","",687,709);
$z[2][4]['name']="address";
$z[3]=Array("global","",779,805);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",854,878);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",1003,1022);
$z[5][4]['name']="fwrx";
$z[6]=Array("global","",1091,1111);
$z[6][4]['name']="email";
$z[7]=Array("global","",1672,1689);
$z[7][4]['name']="qq";
$z[8]=Array("global","",1853,1872);
$z[8][4]['name']="fwrx";
$z[9]=Array("global","",1928,1947);
$z[9][4]['name']="jszc";

?>