<?php
$z[0]=Array("flink","[field:link/]",222,260);
$z[1]=Array("channel","\r\n       <a href=\"[field:typelink/]\" target=\"_self\"><span>[field:typename/]</span></a>\r\n        ",387,547);
$z[1][4]['typeid']="1";
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("global","",690,712);
$z[2][4]['name']="address";
$z[3]=Array("global","",782,808);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",857,881);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",1006,1025);
$z[5][4]['name']="fwrx";
$z[6]=Array("global","",1094,1114);
$z[6][4]['name']="email";
$z[7]=Array("global","",1675,1692);
$z[7][4]['name']="qq";
$z[8]=Array("global","",1856,1875);
$z[8][4]['name']="fwrx";
$z[9]=Array("global","",1931,1950);
$z[9][4]['name']="jszc";

?>