<?php
$z[0]=Array("global","",115,141);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("global","",195,221);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",365,391);
$z[2][4]['name']="cfg_cmspath";
$z[3]=Array("channelartlist","\r\n                <li class=\"{dede:field.currentstyle/}\"><a href=\"{dede:field name='typeurl'/}\" target=\"_self\">{dede:field name='typename'/}</a>\r\n                <div>\r\n                    <ul>\r\n                    {dede:channel type='son' noself='yes'}\r\n                    <li><a href=\"[field:typelink/]\" target=\"_self\">[field:typename/]</a></li>\r\n                    {/dede:channel}\r\n                    </ul>\r\n                </div>\r\n                </li>\r\n                ",554,1110);
$z[3][4]['typeid']="top";
$z[3][4]['currentstyle']="current";

?>