<?php
$z[0]=Array("global","",259,285);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("field","",838,857);
$z[1][4]['name']="title";
$z[2]=Array("global","",858,884);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",925,954);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",994,1052);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",1188,1223);
$z[5][4]['filename']="head.htm";
$z[6]=Array("channel","\r\n      <a href='[field:typeurl/]'>[field:typename/]</a>\r\n      ",1548,1732);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a href='~typelink~' class='curr'>~typename~</a>";
$z[7]=Array("field","",1788,1809);
$z[7][4]['name']="content";
$z[8]=Array("include","",2018,2055);
$z[8][4]['filename']="footer.htm";

?>