<?php
$z[0]=Array("global","",259,285);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("field","",838,857);
$z[1][4]['name']="title";
$z[2]=Array("global","",858,884);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",925,954);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",994,1052);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",1272,1307);
$z[5][4]['filename']="head.htm";
$z[6]=Array("arclist","     \r\n                <li><a href=\"[field:arcurl/]\" target=\"_blank\"><img onload=\"loadImage(this,244,367);\" src=\"[field:litpic/]\" /></a></li>\r\n                 ",8494,8713);
$z[6][4]['typeid']="16";
$z[6][4]['titlelen']="42";
$z[6][4]['row']="9";
$z[7]=Array("type","[field:typeurl /]",9189,9241);
$z[7][4]['typeid']="16";
$z[8]=Array("include","",9343,9380);
$z[8][4]['filename']="footer.htm";

?>