<?php
$z[0]=Array("global","",259,285);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("global","",838,864);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",908,938);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",975,1002);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",1375,1401);
$z[4][4]['name']="cfg_cmspath";
$z[5]=Array("global","",1574,1600);
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("channelartlist","\r\n                <li class=\"{dede:field.currentstyle/}\"><a href=\"{dede:field name='typeurl'/}\" target=\"_self\">{dede:field name='typename'/}</a>\r\n                <div>\r\n                    <ul>\r\n                    {dede:channel type='son' noself='yes'}\r\n                    <li><a href=\"[field:typelink/]\" target=\"_self\">[field:typename/]</a></li>\r\n                    {/dede:channel}\r\n                    </ul>\r\n                </div>\r\n                </li>\r\n                ",1771,2327);
$z[6][4]['typeid']="top";
$z[6][4]['currentstyle']="current";
$z[7]=Array("type","[field:typeurl/]",3675,3725);
$z[7][4]['typeid']="9";
$z[8]=Array("type","[field:typeurl/]",4645,4695);
$z[8][4]['typeid']="8";
$z[9]=Array("type","[field:typeurl/]",5303,5354);
$z[9][4]['typeid']="10";
$z[10]=Array("arclist","\r\n                                        <li><a href=\"[field:arcurl/]\" target=\"_blank\"><img onload=\"loadImage(this,244,367);\" src=\"[field:litpic/]\" /></a></li>\r\n                        ",6471,6717);
$z[10][4]['typeid']="16";
$z[10][4]['row']="10";
$z[10][4]['titlelen']="32";
$z[11]=Array("arclist","\r\n                                        <li><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" /></a></li>\r\n                        ",7145,7357);
$z[11][4]['typeid']="15";
$z[11][4]['row']="10";
$z[11][4]['titlelen']="32";
$z[12]=Array("arclist","\r\n                                        <li><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" /></a></li>\r\n                        ",7761,7973);
$z[12][4]['typeid']="17";
$z[12][4]['row']="10";
$z[12][4]['titlelen']="32";
$z[13]=Array("include","",8817,8854);
$z[13][4]['filename']="footer.htm";

?>