<?php
$z[0]=Array("global","",259,285);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("field","",838,857);
$z[1][4]['name']="title";
$z[2]=Array("global","",858,884);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",925,954);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",994,1052);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",1272,1307);
$z[5][4]['filename']="head.htm";
$z[6]=Array("include","",9193,9230);
$z[6][4]['filename']="footer.htm";

?>