<?php
$z[0]=Array("global","",259,285);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("field","",762,781);
$z[1][4]['name']="title";
$z[2]=Array("global","",782,808);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",849,878);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",918,976);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",1196,1231);
$z[5][4]['filename']="head.htm";
$z[6]=Array("channel","\r\n      <a href='[field:typeurl/]'>[field:typename/]</a>\r\n      ",1556,1740);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a href='~typelink~' class='curr'>~typename~</a>";
$z[7]=Array("list","             \r\n            <li class=\"\">\r\n              <div class=\"pic\"> <a href=\"[field:arcurl/]\" target=\"_blank\"><img onload=\"loadImage(this,384,262);\" src=\"[field:litpic/]\" /></a> <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                <div class=\"ball_box\"></div>\r\n                </a> </div>\r\n              <div class=\"word clearfix\"> <a href=\"[field:arcurl/]\" target=\"_blank\"> <span>[field:title/]</span> <b></b> </a> </div>\r\n            </li>\r\n            ",1873,2377);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",2454,2510);
$z[8][4]['listitem']="pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2723,2760);
$z[9][4]['filename']="footer.htm";

?>